services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: matatu-postgres
    environment:
      POSTGRES_DB: matatu_fleet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/shared/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - matatu-network

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    container_name: matatu-redis
    ports:
      - "6379:6379"
    networks:
      - matatu-network

  # Auth Service
  auth-service:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: matatu-auth
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/matatu_fleet
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - matatu-network
    volumes:
      - ./backend/services/auth:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Note: Fleet Service, Booking Service, and Frontend will be added in future stories
  # Currently only Auth Service is implemented

volumes:
  postgres_data:

networks:
  matatu-network:
    driver: bridge
